MODEL:
    BACKBONE: "resnet18"
    USE_PRETRAINED_BACKBONE: True

    INPUT_SIZE:
        WIDTH: 512
        HEIGHT: 512
    
    STRIDE: 8
    UPSAMPLING: "NEAREST"
    COUPLED_LOCALIZATION_BRANCH: True
    USE_MOSAIC: False
    USE_MIXUP: False

    CLASSES: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]
